import { auth } from '@/auth';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';
import React from 'react';
import { Toaster } from 'sonner';
import './globals.css';

const inter = Inter({ subsets: ['latin'], weight: ['500'] });

export const metadata: Metadata = {
  title: 'Next Auth V5',
  description: 'Generated by Kazim Kayhan',
  icons: '/facicon.ico',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body
          className={cn(
            inter.className,
            'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary to-secondary'
          )}
        >
          {children}
          <Toaster position='bottom-right' richColors />
        </body>
      </html>
    </SessionProvider>
  );
}
