import { auth } from '@/auth';
import LoginButton from '@/components/auth/login-button';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { Poppins } from 'next/font/google';

const poppins = Poppins({ subsets: ['latin'], weight: ['600'] });

export default async function Home() {
  const session = await auth();
  console.log('🚀 ~ Home ~ session:', session);
  return (
    <main className='h-full flex flex-col justify-center items-center'>
      <div className='space-y-6 text-center'>
        <h1 className={cn('text-6xl font-bold text-foreground drop-shadow-md', poppins.className)}>
          🔐Next Auth V5
        </h1>
        <p className='text-2xl text-foreground'>Generated by Kazim Kayhan</p>
        <LoginButton>
          <Button variant='secondary' size='lg'>
            Sign in
          </Button>
        </LoginButton>
      </div>
    </main>
  );
}
