import {
  AlertTriangle,
  AlertTriangleIcon,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleIcon,
  Command,
  CreditCard,
  Delete,
  Edit,
  File,
  FileText,
  GoalIcon,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  RefreshCcw,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
} from 'lucide-react';

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  edit: Edit,
  delete: Delete,
  refresh: RefreshCcw,
  check: Check,
  goal: GoalIcon,
  alert: AlertTriangleIcon,
  circleIcon: CircleIcon,
};
